"""Generated from SoyoiMod-Rebuild. Do not edit by hand."""

SOURCE_INFO = {'source_name': 'SoyoiMod-Rebuild',
 'source_digest': 'cdb178eac950d105a47d4df5d62154a557cf60601de0eb5b7355ef37b0c4bf3f',
 'reward_card_count': 80,
 'material_count': 17,
 'note': 'Card text is ported; cards marked requires_custom_logic need combat hooks.'}

REWARD_CARD_DATA = [{'id': 'soyoi_reward_001',
  'runtime_id': 1,
  'name': '拼豆弹射',
  'base_text': '造成9点伤害。生成1张拼豆色包。',
  'upgraded_text': '造成13点伤害。生成1张拼豆色包。',
  'portrait': 'soyoi_perler_pattern.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 9.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 13.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_002',
  'runtime_id': 2,
  'name': '罐体敲击',
  'base_text': '造成8点伤害。生成1张喷漆罐。',
  'upgraded_text': '造成11点伤害。生成1张喷漆罐。',
  'portrait': 'soyoi_drying_paint.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 8.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 11.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_003',
  'runtime_id': 3,
  'name': '电池点火',
  'base_text': '造成7点伤害。生成1张纽扣电池。',
  'upgraded_text': '造成10点伤害。生成1张纽扣电池。',
  'portrait': 'soyoi_at_the_limit.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 7.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 10.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_004',
  'runtime_id': 4,
  'name': '空白胸牌',
  'base_text': '造成6点伤害。若没有素材，生成吧唧底坯并加工到此牌。',
  'upgraded_text': '造成9点伤害。若没有素材，选择生成吧唧底坯或拼豆色包并加工到此牌。',
  'portrait': 'soyoi_badge_lamination.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 6.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 9.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_005',
  'runtime_id': 5,
  'name': '整面招贴',
  'base_text': '对所有敌人造成3点伤害。本回合每打出1件素材，重复1次，总计至多4次。',
  'upgraded_text': '对所有敌人造成4点伤害。本回合每打出1件素材，重复1次，总计至多5次。',
  'portrait': 'soyoi_large_perler_board.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'all_enemies',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 3.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 4.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_006',
  'runtime_id': 6,
  'name': '压合吊牌',
  'base_text': '造成 {MaterialScaled:diff()} 点伤害。每件复合素材使其增加10点。',
  'upgraded_text': '造成 {MaterialScaled:diff()} 点伤害。每件复合素材使其增加14点。',
  'portrait': 'soyoi_test_fit.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 12.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 16.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_007',
  'runtime_id': 7,
  'name': '裁片包扎',
  'base_text': '获得8点格挡。生成1张不织布裁片。',
  'upgraded_text': '获得11点格挡。生成1张不织布裁片。',
  'portrait': 'soyoi_felt_cutout.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 8.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 11.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_008',
  'runtime_id': 8,
  'name': '活页装订',
  'base_text': '抽1张牌。生成1张活页夹环。',
  'upgraded_text': '抽1张牌。生成1张活页夹环。',
  'portrait': 'soyoi_blanket_stitch.png',
  'cost': 1,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'draw_cards', 'amount': 1.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 1.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_009',
  'runtime_id': 9,
  'name': '桌面清点',
  'base_text': '抽2张牌。可以弃1张牌。',
  'upgraded_text': '抽3张牌。可以弃1张牌。',
  'portrait': 'soyoi_before_clock_out.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'draw_cards', 'amount': 2.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_010',
  'runtime_id': 10,
  'name': '轮阅册页',
  'base_text': '抽1张牌。选择两张手牌，交换它们最左侧的素材。',
  'upgraded_text': '抽2张牌。选择两张手牌，交换它们最左侧的素材。',
  'portrait': 'soyoi_spare_material.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'draw_cards', 'amount': 1.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 2.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_011',
  'runtime_id': 11,
  'name': '吧唧试压',
  'base_text': '造成8点伤害。给予1层易伤。生成1张吧唧底坯。',
  'upgraded_text': '造成11点伤害。给予2层易伤。生成1张吧唧底坯。',
  'portrait': 'soyoi_badge_test_press.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 8.0, 'hits': 1},
              {'operation': 'apply_vulnerable', 'amount': 1.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 11.0, 'hits': 1},
                       {'operation': 'apply_vulnerable', 'amount': 2.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_012',
  'runtime_id': 12,
  'name': '拆件',
  'base_text': '造成8点伤害。若目标有虚弱或易伤，取下此牌最左侧素材并获得1点能量。',
  'upgraded_text': '造成11点伤害。若目标有虚弱或易伤，取下此牌最左侧素材，获得1点能量并抽1张牌。',
  'portrait': 'soyoi_disassemble.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 8.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 11.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_013',
  'runtime_id': 13,
  'name': '连续打磨',
  'base_text': '造成3点伤害 {MaterialScaled} 次。本场每为此牌加工1次，增加1段，至多6段。',
  'upgraded_text': '造成3点伤害 {MaterialScaled} 次。本场每为此牌加工1次，增加1段，至多8段。',
  'portrait': 'soyoi_continuous_sanding.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 3.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 3.0, 'hits': 3}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_014',
  'runtime_id': 14,
  'name': '熨烫拼豆',
  'base_text': '造成 {MaterialScaled:diff()} 点伤害3次。每次打出后，本场每段增加2点。',
  'upgraded_text': '造成 {MaterialScaled:diff()} 点伤害3次。每次打出后，本场每段增加3点。',
  'portrait': 'soyoi_ironed_perler.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 5.0, 'hits': 3}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 6.0, 'hits': 3}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_015',
  'runtime_id': 15,
  'name': '流麻封口',
  'base_text': '给予2层虚弱。生成1张流麻胶液。',
  'upgraded_text': '给予3层虚弱。生成1张流麻胶液。',
  'portrait': 'soyoi_flow_mahjong_seal.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'apply_weak', 'amount': 2.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'apply_weak', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_016',
  'runtime_id': 16,
  'name': '叠贴加固',
  'base_text': '获得2层覆甲和2层荆棘。生成1张EVA板。',
  'upgraded_text': '获得3层覆甲和3层荆棘。生成1张EVA板。',
  'portrait': 'soyoi_layered_reinforcement.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_plating', 'amount': 2.0, 'hits': 1},
              {'operation': 'gain_thorns', 'amount': 2.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_plating', 'amount': 3.0, 'hits': 1},
                       {'operation': 'gain_thorns', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_017',
  'runtime_id': 17,
  'name': '预留工位',
  'base_text': '选择1张手牌保留。下回合开始时，生成自封袋并加工到它。',
  'upgraded_text': '选择至多2张手牌保留。下回合开始时，生成自封袋并加工到它们。',
  'portrait': 'soyoi_reserve_space.png',
  'cost': 0,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['innate', 'exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_018',
  'runtime_id': 18,
  'name': '清理桌面',
  'base_text': '将弃牌堆中1张非素材牌置于抽牌堆顶。生成1张回收标签。',
  'upgraded_text': '将弃牌堆中1张非素材牌置于抽牌堆顶。生成1张回收标签。',
  'portrait': 'soyoi_clear_table.png',
  'cost': 1,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_019',
  'runtime_id': 19,
  'name': '不织布挂件',
  'base_text': '获得 {MaterialScaled:diff()} 点格挡。本回合每打出1件素材，额外获得4点。',
  'upgraded_text': '获得 {MaterialScaled:diff()} 点格挡。本回合每打出1件素材，额外获得5点。',
  'portrait': 'soyoi_felt_charm.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 7.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 10.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_020',
  'runtime_id': 20,
  'name': '摊位展示',
  'base_text': '本回合获得1点力量和3点活力。若有至少2件素材，再获得1点力量和4点活力。',
  'upgraded_text': '本回合获得1点力量和4点活力。若有至少2件素材，再获得2点力量和6点活力。',
  'portrait': 'soyoi_demonstration_class.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'common',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_temporary_strength', 'amount': 1.0, 'hits': 1},
              {'operation': 'gain_vigor', 'amount': 3.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_temporary_strength', 'amount': 1.0, 'hits': 1},
                       {'operation': 'gain_vigor', 'amount': 4.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_021',
  'runtime_id': 21,
  'name': '轮换工位',
  'base_text': '每回合第一次交替打出攻击与技能时，将上一张牌最左侧素材移到后一张；无法移入则合料。',
  'upgraded_text': '每回合前2次交替打出攻击与技能时，将上一张牌最左侧素材移到后一张；无法移入则合料。',
  'portrait': 'soyoi_turn_back_hand.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_022',
  'runtime_id': 22,
  'name': '批量制作',
  'base_text': '每回合第一次生成普通或一次性素材时，复制它。若本回合加工过，改为将两件合料。',
  'upgraded_text': '每回合前2次生成普通或一次性素材时，复制它。若本回合加工过，改为将两件合料。',
  'portrait': 'soyoi_craft_offcuts.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_023',
  'runtime_id': 23,
  'name': '返场加演',
  'base_text': '每回合第一次打出有素材的牌后，将其返回手牌、素材左移一格，本回合耗能增加1。',
  'upgraded_text': '每回合第一次打出有素材的牌后，将其返回手牌、素材左移一格。',
  'portrait': 'soyoi_turn_forward_hand.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_024',
  'runtime_id': 24,
  'name': '精密连刻',
  'base_text': '造成4点伤害 {MaterialScaled} 次。每种不同的素材效果增加1段，至多5段。',
  'upgraded_text': '造成6点伤害 {MaterialScaled} 次，至多6段。',
  'portrait': 'soyoi_precision_carving.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 4.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 6.0, 'hits': 2}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_025',
  'runtime_id': 25,
  'name': '堆料重击',
  'base_text': '造成 {MaterialScaled:diff()} 点伤害。每件复合素材使其增加15点。有2件复合素材时返还1点能量，3件时返还2点。',
  'upgraded_text': '造成 {MaterialScaled:diff()} 点伤害。每件复合素材使其增加20点。有2件复合素材时返还1点能量，3件时返还2点。',
  'portrait': 'soyoi_material_smash.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 18.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 24.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_026',
  'runtime_id': 26,
  'name': '交付展示',
  'base_text': '对所有敌人造成 {MaterialScaled:diff()} 点伤害。本场每为此牌加工1次，增加4点。',
  'upgraded_text': '对所有敌人造成 {MaterialScaled:diff()} 点伤害。本场每为此牌加工1次，增加6点。',
  'portrait': 'soyoi_showcase.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'all_enemies',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 12.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 16.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_027',
  'runtime_id': 27,
  'name': '周边选材',
  'base_text': '抽2张牌。选择生成1张一次性素材并加工到1张手牌；该牌本回合耗能为0。',
  'upgraded_text': '抽3张牌。该牌同时获得保留。',
  'portrait': 'soyoi_material_selection.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'draw_cards', 'amount': 2.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_028',
  'runtime_id': 28,
  'name': '图案复刻',
  'base_text': '获得7点格挡。选择两张手牌，将第一张最左侧素材的复制件加工到第二张。',
  'upgraded_text': '获得10点格挡。改为复制整个复合素材。',
  'portrait': 'soyoi_copy_mold.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 7.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 10.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_029',
  'runtime_id': 29,
  'name': '整理工位',
  'base_text': '抽3张牌。选择1张手牌置顶；下次抽到它时，复制其最左侧素材。',
  'upgraded_text': '抽3张牌。选择1张手牌置顶；下次抽到它时，复制其最左侧素材，且下次打出前耗能为0。',
  'portrait': 'soyoi_organize_station.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'draw_cards', 'amount': 3.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_030',
  'runtime_id': 30,
  'name': '应急修补',
  'base_text': '获得12点格挡。可以拆除任意牌上的1件诅咒素材，再复制消耗堆中1件普通素材填入原槽。',
  'upgraded_text': '获得16点格挡并抽1张牌。可以拆除任意牌上的1件诅咒素材，再复制消耗堆中1件普通素材填入原槽。',
  'portrait': 'soyoi_emergency_repair.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'gain_block', 'amount': 12.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 16.0, 'hits': 1},
                       {'operation': 'draw_cards', 'amount': 1.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_031',
  'runtime_id': 31,
  'name': '摊位备货',
  'base_text': '选择生成2张不同的普通素材并加工到手牌；若选择同一张牌，两件素材先合料。',
  'upgraded_text': '选择生成2张不同的普通素材并加工到手牌；若选择同一张牌，两件素材先合料。完成后获得10点格挡。',
  'portrait': 'soyoi_day_prep.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 10.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_032',
  'runtime_id': 32,
  'name': '废料利用',
  'base_text': '每回合第2次有牌被消耗后，将最近消耗的素材返回手牌；没有素材则抽1张牌。',
  'upgraded_text': '每回合第1次和第3次有牌被消耗后，将最近消耗的素材返回手牌；没有素材则抽1张牌。',
  'portrait': 'soyoi_use_scraps.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_033',
  'runtime_id': 33,
  'name': '材料清单',
  'base_text': '每回合生成第2种不同素材时，获得1点能量并抽2张牌。',
  'upgraded_text': '每回合第一次生成素材时，获得1点能量并抽2张牌。',
  'portrait': 'soyoi_cost_accounting.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_034',
  'runtime_id': 34,
  'name': '刻刀连舞',
  'base_text': '造成3点伤害 {MaterialScaled} 次。此牌每有1件素材，增加1段。',
  'upgraded_text': '造成3点伤害 {MaterialScaled} 次。此牌每有1件素材，增加2段。',
  'portrait': 'soyoi_knife_dance.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 3.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_035',
  'runtime_id': 35,
  'name': '周边投递',
  'base_text': '造成11点伤害。可以加工1件正向素材；若加工，将此牌置于抽牌堆顶。',
  'upgraded_text': '造成15点伤害。若加工，将此牌返回手牌且本回合耗能增加1。',
  'portrait': 'soyoi_throw_prototype.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 11.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 15.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_036',
  'runtime_id': 36,
  'name': '返工风暴',
  'base_text': '对所有敌人造成14点伤害。每有1个空槽，最左侧正向素材额外结算1次。',
  'upgraded_text': '对所有敌人造成18点伤害。每件正向素材各额外结算1次。',
  'portrait': 'soyoi_rework_storm.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'all_enemies',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 14.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 18.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_037',
  'runtime_id': 37,
  'name': '压线完成',
  'base_text': '造成18点伤害。若本回合打出过素材，抽1张牌并将此牌返回手牌，本回合耗能增加1；否则给予2层易伤。',
  'upgraded_text': '造成24点伤害。若本回合打出过素材，抽2张牌并将此牌返回手牌；否则给予3层易伤。',
  'portrait': 'soyoi_deadline_finish.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 18.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 24.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_038',
  'runtime_id': 38,
  'name': '深夜清单',
  'base_text': '选择1张手牌保留。下回合开始时，将消耗堆最上方素材加工到它；没有则获得1点能量。',
  'upgraded_text': '选择至多2张手牌保留。下回合开始时，依次将消耗堆最上方素材加工到它们；没有则获得1点能量。',
  'portrait': 'soyoi_night_checklist.png',
  'cost': 0,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_039',
  'runtime_id': 39,
  'name': '自封袋收纳',
  'base_text': '获得9点格挡。若此牌从上回合保留，先结算其全部素材，再获得1点能量。',
  'upgraded_text': '获得13点格挡。若此牌从上回合保留，先结算其全部素材，最左侧素材再结算1次，再获得1点能量。',
  'portrait': 'soyoi_overnight_glue.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 9.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 13.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_040',
  'runtime_id': 40,
  'name': '改色重排',
  'base_text': '取下任意牌上的1件正向素材，再选择1件手牌素材填入原槽。抽1张牌。',
  'upgraded_text': '取下任意牌上的1件正向素材，再选择1件手牌素材填入原槽。抽2张牌；取下的素材本回合不触发消耗联动。',
  'portrait': 'soyoi_revise_draft.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'draw_cards', 'amount': 1.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 2.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_041',
  'runtime_id': 41,
  'name': '清掉废稿',
  'base_text': '可以消耗弃牌堆中1张牌：攻击牌对所有敌人造成8点伤害；技能牌获得10点格挡；能力牌获得1点能量。',
  'upgraded_text': '可以消耗弃牌堆中1张牌：攻击牌对所有敌人造成12点伤害；技能牌获得14点格挡；能力牌获得1点能量并抽1张牌。',
  'portrait': 'soyoi_remove_drafts.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_042',
  'runtime_id': 42,
  'name': '余温',
  'base_text': '每回合第2次有牌被消耗后，获得4层覆甲。',
  'upgraded_text': '获得6层覆甲。',
  'portrait': 'soyoi_remaining_heat.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_043',
  'runtime_id': 43,
  'name': '临界灵感',
  'base_text': '每回合第一张耗能被降至0的牌，打出时最左侧素材额外结算1次。',
  'upgraded_text': '每回合前2张耗能被降至0的牌，打出时最左侧素材额外结算1次。',
  'portrait': 'soyoi_boundary_inspiration.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_044',
  'runtime_id': 44,
  'name': '零点切割',
  'base_text': '造成10点伤害。若此牌耗能为0，本次打出时每个空槽视作最右侧素材的复制件。',
  'upgraded_text': '造成14点伤害。若此牌耗能为0，本次打出时每个空槽视作最右侧素材的复制件。',
  'portrait': 'soyoi_midnight_cut.png',
  'cost': 1,
  'upgraded_cost': 0,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 10.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 14.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_045',
  'runtime_id': 45,
  'name': '拆坏重做',
  'base_text': '造成12点伤害。可以消耗1件普通素材并生成1张一次性素材；若为复合素材，改为生成2张并自动合料。',
  'upgraded_text': '造成17点伤害。生成的素材本回合加工费用为0。',
  'portrait': 'soyoi_salvage_impact.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 12.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 17.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_046',
  'runtime_id': 46,
  'name': '反复雕刻',
  'base_text': '造成8点伤害 {MaterialScaled} 次。生成拼豆色包并加工到此牌；满槽时自动合料。每次因此合料，本场增加1段。',
  'upgraded_text': '造成10点伤害 {MaterialScaled} 次。每次合料增加2段。',
  'portrait': 'soyoi_repeated_carving.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 8.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 10.0, 'hits': 2}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_047',
  'runtime_id': 47,
  'name': '不眠防线',
  'base_text': '获得 {MaterialScaled:diff()} 点格挡。若从上回合保留，本场增加4点并额外结算最左侧素材，至多3次。',
  'upgraded_text': '获得 {MaterialScaled:diff()} 点格挡。若从上回合保留，本场增加5点并额外结算最左侧素材。',
  'portrait': 'soyoi_sleepless_guard.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 8.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 11.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_048',
  'runtime_id': 48,
  'name': '精力透支',
  'base_text': '获得2点能量并抽2张牌。回合结束时，若本回合没有打出素材，失去6点生命。',
  'upgraded_text': '获得2点能量并抽3张牌。回合结束时，若本回合没有打出素材，失去4点生命。',
  'portrait': 'soyoi_overdraw_energy.png',
  'cost': 0,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'gain_energy', 'amount': 2.0, 'hits': 1},
              {'operation': 'draw_cards', 'amount': 2.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_energy', 'amount': 2.0, 'hits': 1},
                       {'operation': 'draw_cards', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_049',
  'runtime_id': 49,
  'name': '周边返修',
  'base_text': '将消耗堆中1张攻击牌放入手牌，把消耗堆最上方素材的复制件加工到它；本回合耗能降低1。',
  'upgraded_text': '将消耗堆中1张攻击或技能牌放入手牌，把消耗堆最上方素材的复制件加工到它；本回合耗能降低1。',
  'portrait': 'soyoi_recast.png',
  'cost': 1,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_050',
  'runtime_id': 50,
  'name': '临界缓冲',
  'base_text': '获得8点格挡。选择消耗堆中1件素材，本回合将其效果临时加工到1张手牌；不占素材位。',
  'upgraded_text': '获得12点格挡；可以选择复合素材。',
  'portrait': 'soyoi_boundary_buffer.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 8.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 12.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_051',
  'runtime_id': 51,
  'name': '最终检查',
  'base_text': '抽2张牌。选择1张手牌：未升级则升级并保留；已升级则本回合耗能为0。',
  'upgraded_text': '抽3张牌。选择1张手牌：未升级则升级并保留；已升级则本回合耗能为0。',
  'portrait': 'soyoi_final_check.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'draw_cards', 'amount': 2.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'draw_cards', 'amount': 3.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_052',
  'runtime_id': 52,
  'name': '社团手作课',
  'base_text': '每回合第一次加工后获得1点能量；第一次合料后，该成品本回合额外结算1次。',
  'upgraded_text': '每回合第一次加工后获得1点能量；第一次合料后，该成品本回合额外结算2次。',
  'portrait': 'soyoi_public_workshop.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_053',
  'runtime_id': 53,
  'name': '夜间回流',
  'base_text': '回合结束时，从弃牌堆选择1张牌置顶，并将本回合最后消耗的素材复制加工到它。',
  'upgraded_text': '回合结束时，从弃牌堆选择1张牌置顶，并将本回合最后消耗的素材复制加工到它；该牌下次打出前耗能降低1。',
  'portrait': 'soyoi_night_reflux.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_054',
  'runtime_id': 54,
  'name': '针脚连排',
  'base_text': '获得 {MaterialScaled} 点临时力量。造成4点伤害5次。每件复合素材按组件数提供临时力量。',
  'upgraded_text': '获得 {MaterialScaled} 点临时力量。造成5点伤害5次；每件复合素材额外提供1点。',
  'portrait': 'soyoi_stitching_row.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'uncommon',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 4.0, 'hits': 5}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 5.0, 'hits': 5}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_055',
  'runtime_id': 55,
  'name': '描摹图纸',
  'base_text': '选择1张非能力手牌，生成其耗能为0并消耗的复制品。若原牌三槽已满，复制品保留其最左侧素材。',
  'upgraded_text': '选择1张非能力手牌，生成其已升级、耗能为0并消耗的复制品。若原牌三槽已满，复制品保留整个最左侧复合素材。',
  'portrait': 'soyoi_draw_pattern.png',
  'cost': 1,
  'upgraded_cost': 0,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_056',
  'runtime_id': 56,
  'name': '裁不织布',
  'base_text': '获得9点格挡。选择生成不织布裁片或EVA板；若拥有覆甲，改为生成两者、先合料再加工到手牌。',
  'upgraded_text': '获得13点格挡；合料中再加入加厚EVA板。',
  'portrait': 'soyoi_sort_parts.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'uncommon',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'gain_block', 'amount': 9.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 13.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_057',
  'runtime_id': 57,
  'name': '最后通牒',
  'base_text': '造成36点伤害，给予3层易伤和虚弱，再为此牌加工打结挂绳。若这是第2件诅咒素材，重复本牌本体并消耗。',
  'upgraded_text': '造成48点伤害，给予4层易伤和虚弱，再为此牌加工打结挂绳。若这是第2件诅咒素材，重复本牌本体并消耗。',
  'portrait': 'soyoi_ultimatum.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 36.0, 'hits': 1},
              {'operation': 'apply_vulnerable', 'amount': 3.0, 'hits': 1},
              {'operation': 'apply_weak', 'amount': 3.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 48.0, 'hits': 1},
                       {'operation': 'apply_vulnerable', 'amount': 4.0, 'hits': 1},
                       {'operation': 'apply_weak', 'amount': 4.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_058',
  'runtime_id': 58,
  'name': '摊位清仓',
  'base_text': '对所有敌人造成 {MaterialScaled:diff()} 点伤害。消耗手牌中所有非永久正向素材：普通素材增加6点，一次性素材增加12点。',
  'upgraded_text': '对所有敌人造成 {MaterialScaled:diff()} 点伤害。消耗手牌中所有非永久正向素材：普通素材增加8点，一次性素材增加16点。',
  'portrait': 'soyoi_finished_explosion.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'all_enemies',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'damage', 'amount': 20.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 28.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_059',
  'runtime_id': 59,
  'name': '展台坍塌',
  'base_text': '对所有敌人造成 {MaterialScaled:diff()} 点伤害。牌组中每件正向素材增加5点。随后收集每张牌最左侧素材，溢出时合料。',
  'upgraded_text': '对所有敌人造成 {MaterialScaled:diff()} 点伤害。牌组中每件正向素材增加7点。随后收集每张牌最左侧素材，溢出时合料。',
  'portrait': 'soyoi_collapsing_display.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'all_enemies',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 18.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 24.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_060',
  'runtime_id': 60,
  'name': '一刀定型',
  'base_text': '造成 {MaterialScaled:diff()} 点伤害。未击杀则本场增加6点；击杀则增加18点、获得1点能量并返回手牌。',
  'upgraded_text': '造成 {MaterialScaled:diff()} 点伤害。未击杀则本场增加8点；击杀则增加24点、获得1点能量并返回手牌。',
  'portrait': 'soyoi_one_cut_finish.png',
  'cost': 0,
  'upgraded_cost': 0,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'damage', 'amount': 18.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 24.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_061',
  'runtime_id': 61,
  'name': '废稿再利用',
  'base_text': '获得15点格挡。消耗手牌与弃牌堆中的状态牌；每消耗1张，依次额外结算此牌1件素材。',
  'upgraded_text': '获得20点格挡；结算复合素材时整件结算。',
  'portrait': 'soyoi_tear_it_all_down.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'gain_block', 'amount': 15.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 20.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_062',
  'runtime_id': 62,
  'name': '完美复刻',
  'base_text': '选择任意牌上的1件正向素材，生成其永久复制品，再以打结挂绳替换原槽。本场限1次。',
  'upgraded_text': '选择任意牌上的1件正向素材，生成其永久复制品。本场限1次。',
  'portrait': 'soyoi_perfect_replica.png',
  'cost': 2,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_063',
  'runtime_id': 63,
  'name': '倒转表盘',
  'base_text': '弃掉手牌，再抽等量牌。每弃掉1张有素材的牌，所有敌人本回合失去2点力量。',
  'upgraded_text': '每张改为失去3点力量。',
  'portrait': 'soyoi_flip_watch.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_064',
  'runtime_id': 64,
  'name': '通宵杰作',
  'base_text': '每回合第一次打出有复合素材的牌时，额外结算最左侧复合素材；若三槽均为复合素材，再重复牌面效果。',
  'upgraded_text': '每回合前2次打出有复合素材的牌时，额外结算最左侧复合素材；若三槽均为复合素材，再重复牌面效果。',
  'portrait': 'soyoi_overnight_masterpiece.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_065',
  'runtime_id': 65,
  'name': '连夜赶工',
  'base_text': '每回合第一次有牌返回手牌时，抽1张牌并获得1点能量，再把上一张牌最左侧素材移到返回牌。',
  'upgraded_text': '每回合前2次有牌返回手牌时，抽1张牌并获得1点能量，再把上一张牌最左侧素材移到返回牌。',
  'portrait': 'soyoi_overtime_chain.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_066',
  'runtime_id': 66,
  'name': '高压专注',
  'base_text': '获得1点力量。每回合第一次打出有至少2件素材的牌后，获得1点力量和1点能量；若三槽均为复合素材，再将其返回手牌。',
  'upgraded_text': '获得2点力量。每回合第一次打出有至少2件素材的牌后，获得2点力量和1点能量；若三槽均为复合素材，再将其返回手牌。',
  'portrait': 'soyoi_high_pressure_focus.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_strength', 'amount': 1.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_strength', 'amount': 2.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_067',
  'runtime_id': 67,
  'name': '欠下的工期',
  'base_text': '造成 {MaterialScaled:diff()} 点伤害2次。每次打出后，本场耗能增加1、每段增加6；耗能达到3时归零，并合并最左侧两件素材。',
  'upgraded_text': '造成 {MaterialScaled:diff()} 点伤害2次。每次打出后，本场耗能增加1、每段增加8；耗能达到3时归零，并合并最左侧两件素材。',
  'portrait': 'soyoi_owed_deadline.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 12.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 15.0, 'hits': 2}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_068',
  'runtime_id': 68,
  'name': '双相切割',
  'base_text': '造成15点伤害2次。奇数次打出额外结算最左侧素材，偶数次额外结算最右侧素材。',
  'upgraded_text': '造成19点伤害2次；额外结算整件复合素材。',
  'portrait': 'soyoi_dual_phase_cut.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 15.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 19.0, 'hits': 2}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_069',
  'runtime_id': 69,
  'name': '临界交付',
  'base_text': '造成30点伤害。目标生命过半：给予3层易伤并生成1张一次性素材；否则获得2点能量并将此牌置顶。',
  'upgraded_text': '造成40点伤害。目标生命过半：给予4层易伤并生成1张一次性素材；否则获得2点能量并将此牌置顶。',
  'portrait': 'soyoi_boundary_delivery.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 30.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 40.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_070',
  'runtime_id': 70,
  'name': '闭馆之后',
  'base_text': '对所有敌人造成16点伤害2次。本回合每打出1张其他牌，耗能降低1；降至1及以下时，素材各额外结算1次。',
  'upgraded_text': '对所有敌人造成20点伤害2次。本回合每打出1张其他牌，耗能降低1；降至1及以下时，素材各额外结算1次。',
  'portrait': 'soyoi_after_closing.png',
  'cost': 4,
  'upgraded_cost': 4,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'all_enemies',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 16.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 20.0, 'hits': 2}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_071',
  'runtime_id': 71,
  'name': '流麻装袋',
  'base_text': '获得14点格挡。素材结算后，收回本牌所有正向素材；每件再获得6点格挡。',
  'upgraded_text': '获得18点格挡。素材结算后，收回本牌所有正向素材；每件再获得8点格挡。',
  'portrait': 'soyoi_store_finished_prop.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': True,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 14.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 18.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_072',
  'runtime_id': 72,
  'name': '大休息',
  'base_text': '获得28点格挡。回复6点生命。结束你的回合。',
  'upgraded_text': '获得36点格挡。回复8点生命。结束你的回合。',
  'portrait': 'soyoi_long_rest.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [{'operation': 'gain_block', 'amount': 28.0, 'hits': 1}, {'operation': 'heal', 'amount': 6.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 36.0, 'hits': 1},
                       {'operation': 'heal', 'amount': 8.0, 'hits': 1}],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_073',
  'runtime_id': 73,
  'name': '留到明天',
  'base_text': '保留你的手牌。结束你的回合。下回合抽2张牌并获得2点能量。',
  'upgraded_text': '保留你的手牌。结束你的回合。下回合抽3张牌并获得3点能量。',
  'portrait': 'soyoi_leave_for_tomorrow.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': ['exhaust'],
  'upgraded_keywords': ['exhaust'],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_074',
  'runtime_id': 74,
  'name': '积压工期',
  'base_text': '每回合前2次有牌的费用增加时，获得6点格挡和1点活力。',
  'upgraded_text': '每回合前3次有牌的费用增加时，获得8点格挡和2点活力。',
  'portrait': 'soyoi_accumulated_experience.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_075',
  'runtime_id': 75,
  'name': '强制续班',
  'base_text': '每回合结束时，若本回合打出至少3张牌，下回合抽1张牌并获得2点能量。',
  'upgraded_text': '每回合结束时，若本回合打出至少2张牌，下回合抽2张牌并获得2点能量。',
  'portrait': 'soyoi_forced_overtime.png',
  'cost': 2,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_076',
  'runtime_id': 76,
  'name': '彻夜不眠',
  'base_text': '你的非素材手牌不再在回合结束时弃掉。每回合开始时，每有1张因此保留的牌，失去1点生命，至多5点。',
  'upgraded_text': '你的非素材手牌不再在回合结束时弃掉。每回合开始时，每有1张因此保留的牌，失去1点生命，至多5点。',
  'portrait': 'soyoi_all_nighter.png',
  'cost': 3,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_077',
  'runtime_id': 77,
  'name': '双刻',
  'base_text': '目标每有易伤或虚弱中的一种，获得3点活力。造成6点伤害2次。',
  'upgraded_text': '目标每有易伤或虚弱中的一种，获得4点活力。造成8点伤害2次。',
  'portrait': 'soyoi_double_notch.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'attack',
  'rarity': 'rare',
  'target': 'any_enemy',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'damage', 'amount': 6.0, 'hits': 2}],
  'upgraded_effects': [{'operation': 'damage', 'amount': 8.0, 'hits': 2}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_078',
  'runtime_id': 78,
  'name': '临时护板',
  'base_text': '获得14点格挡。本回合下一次有牌的费用增加时，抵消此次增加并获得1点能量。',
  'upgraded_text': '获得18点格挡。本回合前2次有牌的费用增加时，抵消此次增加并获得1点能量。',
  'portrait': 'soyoi_temporary_panel.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'skill',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [{'operation': 'gain_block', 'amount': 14.0, 'hits': 1}],
  'upgraded_effects': [{'operation': 'gain_block', 'amount': 18.0, 'hits': 1}],
  'requires_custom_logic': False},
 {'id': 'soyoi_reward_079',
  'runtime_id': 79,
  'name': '按时交付',
  'base_text': '每回合第3张正常打出的攻击或技能牌，本体额外结算1次。结束回合的牌除外。',
  'upgraded_text': '每回合第3张正常打出的攻击或技能牌，本体额外结算1次。结束回合的牌除外。',
  'portrait': 'soyoi_on_time.png',
  'cost': 3,
  'upgraded_cost': 2,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True},
 {'id': 'soyoi_reward_080',
  'runtime_id': 80,
  'name': '喘口气',
  'base_text': '每回合第一次打出费用不低于2的牌后，获得12点格挡并抽1张牌。',
  'upgraded_text': '每回合第一次打出费用不低于2的牌后，获得16点格挡并抽1张牌。',
  'portrait': 'soyoi_catch_breath.png',
  'cost': 1,
  'upgraded_cost': 1,
  'card_type': 'power',
  'rarity': 'rare',
  'target': 'self',
  'is_fusion': False,
  'keywords': [],
  'upgraded_keywords': [],
  'effects': [],
  'upgraded_effects': [],
  'requires_custom_logic': True}]

MATERIAL_DATA = [{'id': 'badge_blank',
  'name': '吧唧底坯',
  'text': '承载牌打出后，给予目标2层易伤。',
  'category': 'normal',
  'effects': [{'operation': 'apply_vulnerable',
               'amount': 2.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'binder_ring',
  'name': '活页夹环',
  'text': '承载牌打出后，抽1张牌。',
  'category': 'normal',
  'effects': [{'operation': 'draw_cards',
               'amount': 1.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'owner',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'button_battery',
  'name': '纽扣电池',
  'text': '承载牌打出后，获得1点能量。',
  'category': 'normal',
  'effects': [{'operation': 'gain_energy',
               'amount': 1.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'owner',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'custom_eva_lining',
  'name': '定制EVA内衬',
  'text': '承载牌打出后，目标获得4点格挡。每场战斗首次触发时，获得1点能量。',
  'category': 'permanent',
  'effects': [{'operation': 'gain_block',
               'amount': 4.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False},
              {'operation': 'gain_energy',
               'amount': 1.0,
               'hits': 1,
               'timing': 'first_carrier_play_each_combat',
               'target': 'owner',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'eva_board',
  'name': 'EVA板',
  'text': '承载牌打出后，目标获得2层覆甲。',
  'category': 'normal',
  'effects': [{'operation': 'gain_plating',
               'amount': 2.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'felt_scrap',
  'name': '不织布裁片',
  'text': '承载牌打出后，目标获得6点格挡。',
  'category': 'normal',
  'effects': [{'operation': 'gain_block',
               'amount': 6.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'flow_mahjong_glue',
  'name': '流麻胶液',
  'text': '承载牌打出后，给予目标2层虚弱。',
  'category': 'normal',
  'effects': [{'operation': 'apply_weak',
               'amount': 2.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'full_perler_tray',
  'name': '满盘拼豆',
  'text': '承载牌打出后，对目标造成4点素材伤害4次。',
  'category': 'one_shot',
  'effects': [{'operation': 'material_damage',
               'amount': 4.0,
               'hits': 4,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': True}]},
 {'id': 'glue_overflow_scrap',
  'name': '溢胶废片',
  'text': '每回合首次打出承载牌后，将1张伤口加入弃牌堆。',
  'category': 'curse',
  'effects': [{'operation': 'add_wound_to_discard',
               'amount': 1.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'owner',
               'once_per_turn': True,
               'consumes_component': False}]},
 {'id': 'perler_color_pack',
  'name': '拼豆色包',
  'text': '承载牌打出后，对目标造成3点素材伤害2次。',
  'category': 'normal',
  'effects': [{'operation': 'material_damage',
               'amount': 3.0,
               'hits': 2,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'permanent_perler_board',
  'name': '常驻拼豆板',
  'text': '承载牌打出后，对目标造成4点素材伤害2次。',
  'category': 'permanent',
  'effects': [{'operation': 'material_damage',
               'amount': 4.0,
               'hits': 2,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'recycle_label',
  'name': '回收标签',
  'text': '每回合首次打出承载牌后，可将弃牌堆中1张其他非素材牌置于抽牌堆顶。',
  'category': 'normal',
  'effects': [{'operation': 'put_other_non_material_from_discard_on_draw_pile',
               'amount': 1.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'owner',
               'once_per_turn': True,
               'consumes_component': False}]},
 {'id': 'rush_lanyard',
  'name': '加急挂绳',
  'text': '承载牌结算后返回手牌；再次打出时获得2点能量。',
  'category': 'one_shot',
  'effects': [{'operation': 'return_carrier_to_hand',
               'amount': 1.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'carrier',
               'once_per_turn': False,
               'consumes_component': True},
              {'operation': 'gain_energy',
               'amount': 2.0,
               'hits': 1,
               'timing': 'after_carrier_next_played',
               'target': 'owner',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'spray_can',
  'name': '喷漆罐',
  'text': '承载牌打出后，目标本回合失去2点力量。',
  'category': 'normal',
  'effects': [{'operation': 'lose_strength_this_turn',
               'amount': 2.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'tangled_lanyard',
  'name': '打结挂绳',
  'text': '承载牌耗能增加1。',
  'category': 'curse',
  'effects': [{'operation': 'increase_carrier_cost',
               'amount': 1.0,
               'hits': 1,
               'timing': 'persistent',
               'target': 'carrier',
               'once_per_turn': False,
               'consumes_component': False}]},
 {'id': 'thick_eva_board',
  'name': '加厚EVA板',
  'text': '承载牌打出后，目标获得6层覆甲。',
  'category': 'one_shot',
  'effects': [{'operation': 'gain_plating',
               'amount': 6.0,
               'hits': 1,
               'timing': 'after_carrier_played',
               'target': 'inherited',
               'once_per_turn': False,
               'consumes_component': True}]},
 {'id': 'zip_bag',
  'name': '自封袋',
  'text': '承载牌获得保留。跨回合保留后，下次耗能降低2，最低为0。',
  'category': 'normal',
  'effects': [{'operation': 'grant_retain',
               'amount': 1.0,
               'hits': 1,
               'timing': 'persistent',
               'target': 'carrier',
               'once_per_turn': False,
               'consumes_component': False},
              {'operation': 'reduce_next_cost',
               'amount': 2.0,
               'hits': 1,
               'timing': 'after_retained_across_turn',
               'target': 'carrier',
               'once_per_turn': False,
               'consumes_component': False}]}]
